### ISSUE TITLE
TypeError: pl.droidsonroids.gif.GifImageView is not a constructor

### ISSUE THREAD

**Issue by RoyiNamir** [bradmartin/nativescript-gif#21]
Hello.

I'm using Angular 5 with Nativescript 4

My app.module is  : 
```
import { registerElement } from "nativescript-angular/element-registry";
registerElement("Gif", () => require("nativescript-gif").Gif);
```
In code I have this : 

```
<StackLayout>
       <Gif src="https://media4.giphy.com/media/3uyIgVxP1qAjS/200.gif" height="200" ></Gif>
    </StackLayout>
```

But we get an error  : 
```
 System.err: com.tns.NativeScriptException:
System.err: Calling js method onCreateView failed
System.err:
System.err: TypeError: pl.droidsonroids.gif.GifImageView is not a constructor
System.err: File: "file:///data/data/org.nativescript.game2/files/app/tns_modules/nativescript-gif/gif.js, line: 17, column: 26
System.err:
System.err: StackTrace:
System.err:     Frame: function:'Gif.createNativeView', file:'file:///data/data/org.nativescript.game2/files/app/tns_modules/nativescript-gif/gif.js', line: 17, column: 27
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.game2/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 492, column: 35
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.game2/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 534, column: 19
System.err:     Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.game2/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.game2/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 855, column: 14
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.game2/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 14
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.game2/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 534, column: 19
System.err:     Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.game2/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.game2/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 855, column: 14
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.game2/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 14
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.game2/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 534, column: 19
System.err:     Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.game2/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.game2/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 855, column: 14
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.game2/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 14
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.game2/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 534, column: 19
System.err:     Frame: function:'ContentView.eachChildView', file:'file:///data/data/org.nativescript.game2/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
System.err:     Frame: function:'PageBase.eachChildView', file:'file:///data/data/org.nativescript.game2/files/app/tns_modules/tns-core-modules/ui/page/page-common.js', line: 120, column: 40
System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.game2/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 855, column: 14
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.game2/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 14
System.err:     Frame: function:'ViewBase._addViewCore', file:'file:///data/data/org.nativescript.game2/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 431, column: 18
System.err:     Frame: function:'ViewBase._addView', file:'file:///data/data/org.nativescript.game2/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 420, column: 14
System.err:     Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'file:///data/data/org.nativescript.game2/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 576, column: 24
System.err:     Frame: function:'FragmentClass.onCreateView', file:'file:///data/data/org.nativescript.game2/files/app/tns_modules/tns-core-modules/ui/frame/fragment.js', line: 27, column: 38
System.err:
```

**Comment by jorotenev** [comment]
Happens on NativeScript Core too (without Angular).

**Comment by bradmartin** [comment]
If on ns4 likely the build of the plugin isn't loading the lib correctly. Try to look at next week, some minor change might be needed in the gradle file. Not sure right now.

**Comment by jorotenev** [comment]
Yes, it's on v4

**Comment by bradmartin** [comment]
4.0.0 published, should fix this.

**Comment by YuraIvanskyi** [comment]
Hello, this issue still occurs on my side, NS 3.4.1 and gif module fresh installed with
`tns plugin add nativescript-gif@3.1.1`
Using plain NS with code:
`xmlns:Gif="nativescript-gif"`
`<Gif:Gif src="https://media4.giphy.com/media/3uyIgVxP1qAjS/200.gif" height="200" />`
And catch an exception: 
`System.err: com.tns.NativeScriptException:
System.err: Calling js method onCreateView failed
System.err: TypeError: pl.droidsonroids.gif.GifImageView is not a constructor
System.err: File: "file:///data/data/org.nativescript.masterDet/files/app/tns_modules/nativescript-gif/gif.js, line: 17, column: 26
System.err: StackTrace:
System.err:     Frame: function:'Gif.createNativeView', file:'file:///data/data/org.nativescript.masterDet/files/app/tns_modules/nativescript-gif/gif.js', line: 17, column: 27
`
... the same error basically.

**Comment by bradmartin** [comment]
Please read this https://bradmartin.net/2016/07/20/ahhh-this-nativescript-plugin-doesnt-work/ - I successfully ran the demo app on NS3.4 and NS4.0 before publishing the updated Gif plugin. So you have a simple cache/build issue that is not loading the native library correctly to your project. I would guess a simple `rm -rf node_modules platforms hooks` then running `tns run android` would fix this for your project. If it does not, then `npm cache clean` to clean the npm cache, seen that cause issues before. Last resort would be something internal in your project's gradle file that could cause an issue if you've modified it with some custom gradle config.

**Comment by rafaelcmrj** [comment]
I still get the error even after remove/clean up everything

**Comment by rafaelcmrj** [comment]
FYI it doesn't load images from the App_Resources folder
